configs:
  1_deactivate_auto_conda_base_config:
    file: ./hub/before-notebook.d/1_deactivate_auto_conda_base.py
  2_set_default_conda_env_config:
    file: ./hub/before-notebook.d/2_set_default_conda_env.py
  3_append_to_notebook_config:
    file: ./hub/before-notebook.d/3_append_to_notebook.py
  4_create_ipython_profile_start_config:
    file: ./hub/before-notebook.d/4_create_ipython_profile_start.py
  5_create_r_libs_path_config:
    file: ./hub/before-notebook.d/5_create_r_libs_path.py
  6_set_jupyter_kernels_config:
    file: ./hub/before-notebook.d/6_set_jupyter_kernels.py
  7_set_python_pip_aliases_config:
    file: ./hub/before-notebook.d/7_set_python_pip_aliases.py
  8_welcome_message_config:
    file: ./hub/before-notebook.d/8_welcome_message.py
  update_path_env_config:
    file: ./hub/jupyter_startup_files/update_path_env.py
  r_environ_config:
    file: ./hub/R/etc/Renviron
  r_server_config:
    file: ./hub/R/conf/rserver.conf

services:
  proxy:
    image: jupyterhub/configurable-http-proxy:4.6.2
    deploy:
      placement:
        constraints: [node.role == manager]
    env_file:
      .env
    ports:
      - "443:443"
    user: 0:0
    volumes:
      - type: bind
        source: ./ssl/certs/jupyterhub
        target: /etc/ssl/certs/jupyterhub
        read_only: true
    command:
      configurable-http-proxy
        --port=8080
        --default-target=https://jupyterhub:8080
        --error-target=https://jupyterhub:8080/hub/error
        --log-level=INFO

  jupyterhub:
    image: ucphhpc/jupyterhub:4.1.6
    deploy:
      placement:
        constraints: [node.role == manager]
    env_file:
      .env
    volumes:
        # The jupyterhub service needs accces to the docker daemon process
        # to launch other services/containers
      - /var/run/docker.sock:/var/run/docker.sock:rw
        # Keep the jhub states such as the db saved during restarts
      - type: volume
        source: jhubstate
        target: /srv/jupyterhub
        # Load the jupyterhub config from /etc/jupyterhub
      - type: bind
        source: ./hub/jupyterhub
        target: /etc/jupyterhub
        read_only: true
    command: jupyterhub -f /etc/jupyterhub/jupyterhub_config.py --log-level=INFO

  docker-image-updater:
    image: ucphhpc/docker-image-updater
    deploy:
      mode: global
      placement:
          constraints:
            - "node.labels.type==cpu"
    environment:
      TZ: ${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: |
      - -interval 1440
      - -update ucphhpc/docker-image-updater
      - -update ucphhpc/datascience-notebook:4.3.6
      - -update ucphhpc/statistics-notebook:4.3.6
      - -update ucphhpc/r-notebook:4.3.6
      - -update ucphhpc/gpu-notebook:4.3.6
      - -update ucphhpc/chemistry-notebook:4.2.4
      - -update ucphhpc/geo-notebook:4.3.6
      - -update ucphhpc/bio-notebook:4.3.6
      - -update ucphhpc/julia-notebook:4.3.6
      - -update ucphhpc/ocean-notebook:4.3.6
      - -update ucphhpc/qsharp-notebook:4.3.6
      - -protect ucphhpc/jupyterhub:4.1.6
      - -protect jupyterhub/configurable-http-proxy:4.6.2
      - -prune
      - -prune-untagged


volumes:
  jhubstate:
    external: true

networks:
  default:
    name: jupyter-service_default
    external: true
